### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by patrick-llgc** [TRI-ML/KP2D#1]
Hi!

Congratulations on the great work! 

Any update on when to release the code? Looking forward to it!

**Comment by ApeCoding** [comment]
+1!
Looking forward to it~

**Comment by Zumbalamambo** [comment]
+1

**Comment by liuming234** [comment]
Looking forward too

**Comment by Zumbalamambo** [comment]
@liuming234 soon

**Comment by dennisbappert** [comment]
And how soon? :)

**Comment by Zumbalamambo** [comment]
@dennisbappert soon after the code has been pushed to the GitHub, we as a public can clone it or download it, install the required libraries and execute the demos to replicate exactly what the paper has explained.

**Comment by Zumbalamambo** [comment]
> And how soon? :)

very soon :P

**Comment by VitorGuizilini-TRI** [comment]
Hi, we have just released inference code, and we are currently working on releasing the training code.

**Comment by neon5d** [comment]
Thank you for sharing your great work. I knew you are preparing for the training code.
Do you have any specific releasing date?

**Comment by AmmarKamoona** [comment]
Hi there, 
Please release the training code. I am looking forward this

**Comment by jumpsnack** [comment]
+1
Looking forward too

**Comment by mamba-wang** [comment]
Thanks for your working!
+1
Looking forward too!

**Comment by mamba-wang** [comment]
Thanks for your working!
+1
Looking forward too!

**Comment by mamba-wang** [comment]
Thanks for your working!
+1
Looking forward too!

**Comment by mamba-wang** [comment]
Thanks for your working!
+1
Looking forward too!

**Comment by Jemmagu** [comment]
Hi @VitorGuizilini-TRI ,
thanks for your great work! I do benefit from your paper.
Also wanna ask when will the training code be released, really really looking forward to that!

big thanks!

**Comment by RaresAmbrus** [comment]
The code is available and I just updated the repo to Pytorch 1.6 to make it easier to use. Let me know if you run into any issues.
