### ISSUE TITLE
Some questions about detector learning

### ISSUE THREAD

**Issue by Bingyang0410** [TRI-ML/KP2D#11]
Hi! 
I am confused about the realization of formula 2 in the section 3.1.
In the keypoint_net.py line 148, it seems that you use meshgrid to generate the center coordinates of each cell, why it can be expressed as row_center and col_center?

**Comment by RaresAmbrus** [comment]
Hi, so each value in the detector map corresponds to the offset from the center of the cell in the original image resolution. We first create the array that represents all the cell centers (line 148) and then add the predicted offsets (line 153), following Eq2 from the paper. I hope that makes sense, but let me know if you have any other questions.
