### ISSUE TITLE
which eval metric should I use to decide stop train?

### ISSUE THREAD

**Issue by captainfffsama** [TRI-ML/KP2D#16]
Thx for you brilliant idea, I have a question about that which eval metric should I refer to know model is over fitting or not fitting?  

Here is the eval metrics change during I set img size 960\*544 and batchsize 1 train  on coco train dataset, eval is on HPatch and img size is 320\*240:
![](https://i.imgur.com/5tDVwFL.png)

It seems that after epoch 3, M Score and Repeatability is all the way down not up...

If I train on my own image dataset ,which eval metric should I refer to stop train?

**Comment by RaresAmbrus** [comment]
As you train for longer Loc_error should be going down, and corr_1 should be going up. As for stopping training, I think corr1 could be a good metric as it's quite strict. But it also depends on potential downstream applications, for example pose estimation, that you could use to check the performance of the network.
