### ISSUE TITLE
Question about the Qualatitive Results

### ISSUE THREAD

**Issue by zxiaomzxm** [TRI-ML/KP2D#17]
Hi, I have used the BFmathcer in evaluation code to draw matched points between image pair, but I got some worse matching result compare to the qualatitive results in the README.md. I wander is there some post-processing procedure I missed?

**Comment by RaresAmbrus** [comment]
Hi - could you maybe check that you get the same quantitative results as we reported? I don't think we used any additional filtering or post-processing on the matches.
