### ISSUE TITLE
How to get Qualatitive Results?

### ISSUE THREAD

**Issue by UmutCosk** [TRI-ML/KP2D#19]
I would like to have the qualitative results like in the readme for image pairs.

How would I set it up?

**Comment by RaresAmbrus** [comment]
Hi, for drawing keypoints on an images we have [this](https://github.com/TRI-ML/KP2D/blob/master/kp2d/utils/keypoints.py#L28) function in the repo. For drawing corrrespondences you could use something like opencv's [drawMatches](https://docs.opencv.org/master/d4/d5d/group__features2d__draw.html#ga62fbedb5206ab2faf411797e7055c90f).

**Comment by zzkslam** [comment]
How can I get the keypoints and descriptors using the pre-trained models?

**Comment by RaresAmbrus** [comment]
Try running:
```
make docker-run COMMAND="python scripts/eval_keypoint_net.py --pretrained_model /data/models/kp2d/v4.ckpt --input /data/datasets/kp2d/HPatches/"
```

You can then get the scores, keypoints and descriptors [here](https://github.com/TRI-ML/KP2D/blob/77633af57d65c5a0cd7609eaeab7e6cb758ca791/kp2d/evaluation/evaluate.py#L46).

**Comment by NoRealLogin** [comment]
Hi everyone,
has someone implemented it yet ? I would have liked to take a look at it before doing it myself.
