### ISSUE TITLE
about the loss of detector 

### ISSUE THREAD

**Issue by ghoshaw** [TRI-ML/KP2D#29]
HI, thanks for your great work! I have a question about the loss in code. 
In Loss part," d_uv_mat_abs = torch.abs(source_uv_warped.view(B,2,-1).unsqueeze(3) - target_uv_pred.view(B,2,-1).unsqueeze(2)) "  is used to calc the uv loss. My question is the source_uv_warped and target_nv_pred should be algined by there, so why we need a hw*hw for distance ?  Directly using "d_uv_mat_abs = torch.abs(source_uv_warped.view(B,2,-1) - target_uv_pred.view(B,2,-1)) is not enough?

**Comment by RaresAmbrus** [comment]
Hmm yes, I think you're right that we may not need that. Did you try running without?

**Comment by ghoshaw** [comment]
No, but I will give it a try. Thanks!
