### ISSUE TITLE
the result is bad for long-term visual location?

### ISSUE THREAD

**Issue by ghoshaw** [TRI-ML/KP2D#30]
Hi, I used kp2d as keypoint and local descriptor and netvlad as global descriptor in hloc for Aachen dataset. The result is very bad. Has anyone done visual location using the method ?

**Comment by RaresAmbrus** [comment]
We haven't tried that. Did you use the pretrained model? Maybe the image resolution is different? The pretrained Coco model performed quite well on KITTI ...

**Comment by ghoshaw** [comment]
Yes, I used the pretrained model.
And I found I used some wrong parameter so the result is bad. It is solved anyway. Thanks.

**Comment by w8128835** [comment]
> 



> Hi, I used kp2d as keypoint and local descriptor and netvlad as global descriptor in hloc for Aachen dataset. The result is very bad. Has anyone done visual location using the method ?

Hello,I use the dockerfile to build the environment,but the docker file doesn't work well;it shows me that
![image](https://user-images.githubusercontent.com/31956796/218902452-9cfa5012-15d6-4292-8929-2d9394473c64.png)

Could you please share your docker file with me? @ghoshaw @RaresAmbrus thank you very much
