### ISSUE TITLE
Why do we need to switch x, y order?

### ISSUE THREAD

**Issue by neon5d** [TRI-ML/KP2D#8]
Hello,

I am very confused about why we need to switch x, y order before warp_keypoints function call?
 Can you explain a little bit about the background of this?
Thank you,
 ```
# Keypoint vector, consisting of (x,y,probability).
keypoints = np.stack([keypoints[0], keypoints[1]], axis=-1)
warp_keypoints(keypoints[:, [1, 0]], H)

def keep_true_keypoints(points, descriptors, H, shape):
        """ Keep only the points whose warped coordinates by H are still inside shape. """
        warped_points = warp_keypoints(_points[:, [1, 0]], H)
        warped_points[:, [0, 1]] = warped_points[:, [1, 0]]
        mask = (warped_points[:, 0] >= 0) & (warped_points[:, 0] < shape[0]) &\
               (warped_points[:, 1] >= 0) & (warped_points[:, 1] < shape[1])
        return points[mask, :], descriptors[mask, :]
```

**Comment by RaresAmbrus** [comment]
Hey - thanks for the question. We kept much of the evaluation similar to other methods for consistency. I'm pretty sure we should be able to do this in a cleaner way. I'll check in more detail and get back to you in a few days.

**Comment by captainfffsama** [comment]
> Hey - thanks for the question. We kept much of the evaluation similar to other methods for consistency. I'm pretty sure we should be able to do this in a cleaner way. I'll check in more detail and get back to you in a few days.

I am confused too. It seems that x,y should not swap...
In the normal scene,conside ![](http://latex.codecogs.com/gif.latex?(x_i,y_i)) map to ![](http://latex.codecogs.com/gif.latex?(x^\prime_i,y^\prime_i))   :
![](https://pic3.zhimg.com/v2-933c50e86f6ebe5f2420d58dbd7d351a_r.jpg)  
the final result is:
![](https://pic3.zhimg.com/v2-4cbcdfd471d4ee7ed736aeaacdf7b936_r.jpg)

But in code ,its seem that:
![](https://raw.githubusercontent.com/captainfffsama/MarkDownPics/master/image/20201222183929.png)
the final result is:
![](https://raw.githubusercontent.com/captainfffsama/MarkDownPics/master/image/20201222184050.png)

then we swap final x,y after `warp_keypoints` finished,but result is not right,is obviouse that:
![](https://raw.githubusercontent.com/captainfffsama/MarkDownPics/master/image/20201222184656.png)

Maybe should not swap x,y?

**Comment by RaresAmbrus** [comment]
Thanks! I've also been looking into this and cleaning up the code. The calculation is correct, but we swap and then swap back in a couple of places which is unnecessary. I'll PR the cleanup fix later today (and I've also updated the repo to pytorch 1.6).

**Comment by RaresAmbrus** [comment]
We just merged a [PR](https://github.com/TRI-ML/KP2D/commit/4d1556702cc28bf2791749c8fdcdbec891c3093d) with the cleanup - hopefully it makes more sense now!
